### ISSUE TITLE
Does this project support higher sample rates WAV file?

### ISSUE THREAD

**Issue by xfce** [elehobica/RPi_Pico_WAV_Player#1]
Does this project support higher sample rates wav file, such as 96kHz, 192kHz

**Comment by elehobica** [comment]
Thanks for your post. No, not yet. I agree that higher sampling rate and bit resolution would be the items this project need to support next. There are two main challenges to support them, one is I2S playback and another is read bitrate from SD card. I believe they're feasible from what I've experienced with rp2040. It will not be so soon, however, I'll start at some timing.

**Comment by xfce** [comment]
Thanks, waiting for that.

**Comment by elehobica** [comment]
Hello, it's been long long time since your inquiry has been posted.
Now I'm working for support of Hi-Res WAV up to 24bit 192KHz. If you're still curious about it, could you please have a look at https://github.com/elehobica/RPi_Pico_WAV_Player/tree/support-hi-res?
I will appreciate any feedbacks.
