### ISSUE TITLE
Compiled file

### ISSUE THREAD

**Issue by DietzWN** [elehobica/RPi_Pico_WAV_Player#2]
Can you put add compiled file (RPi_Pico_WAV_Player.uf) ?

**Comment by elehobica** [comment]
hello. Thanks for your inquiry. please find https://github.com/elehobica/RPi_Pico_WAV_Player/releases/tag/v0.9.2.

**Comment by DietzWN** [comment]
Thanks

**Comment by DietzWN** [comment]
Thanks
