### ISSUE TITLE
GPIO Button

### ISSUE THREAD

**Issue by DietzWN** [elehobica/RPi_Pico_WAV_Player#3]
I just tested with compile firmware, it just display folder, but i can move cursor or change folder.
I'm using GPIO. Do i need to remove pull resistors 4K7 and 2K2 ?

Thanks
Didiet

**Comment by elehobica** [comment]
Thanks for your patience. It seems the issue is as same as #4 , where the symptom is described in detail. Therefore, I'd like to discuss there. If something is different from #4 case, please let me know then.
